/*

 MAP_FOREST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\dell\Documents\2 Proyectos personales\2 Programación\GB_Tile_designer\Archivos_editables\01\fores01_map_tile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_ForestWidth 20
#define map_ForestHeight 18
#define map_ForestBank 0

extern unsigned char map_Forest[];

/* End of MAP_FOREST.H */
